---
title: "Compare outputs by molecule"
author: "Yami Ommar AC"
date: "7/8/2021"
output: html_document
---

Libraries:
```{r libraries}
library(data.table)
library(tidyverse)
```

Paths & sequences
```{r paths}
path_output <- "~/walle_virome/simulations_Feb_2020b/2021/Lengths/length_60/Kraken2_output/"
viral_sequences <- c("NC_001338.1", "NC_008517.1", "NC_008976.1", "NC_026238.1")
simulated_reads <- fread(input = "~/walle_virome/simulations_Feb_2020b/2021/Lengths/length_60/total_simulated_reads_accession.tsv")

rna_sequences <- c("NC_029549.1", "NC_029923.1", "NC_037587.1", "NC_027426.1",
                   "NC_027715.1", "NC_028098.1", "NC_028397.1", "NC_028259.1",
                   "NC_028474.1", "NC_024910.1", "NC_033788.1", "NC_033847.1",
                   "NC_034243.1", "NC_018403.1", "NC_018383.1", "NC_031139.1",
                   "NC_031137.1", "NC_032113.1", "NC_032269.1", "NC_032986.1",
                   "NC_032886.1", "NC_032742.1", "NC_032809.1", "NC_033241.1",
                   "NC_033449.1", "NC_035118.1", "NC_036468.1", "NC_020103.1",
                   "NC_020439.1", "NC_021223.1", "NC_025432.1", "NC_025795.1",
                   "NC_026246.1", "NC_026811.2", "NC_026921.1", "NC_006307.2",
                   "NC_003011.1", "NC_003820.1", "NC_003837.1", "NC_003545.1",
                   "NC_007742.1", "NC_003835.1", "NC_002561.1", "NC_002063.1",
                   "NC_001846.1", "NC_004144.1", "NC_005029.1", "NC_010706.1",
                   "NC_014397.1", "NC_010350.1", "NC_009028.2", "NC_007667.1",
                   "NC_007555.1", "NC_003606.1", "NC_004830.2", "NC_001834.1",
                   "NC_010757.1", "NC_038430.1", "NC_038775.1", "NC_038920.1",
                   "NC_039014.1", "NC_038581.1", "NC_039185.1")
```

data.table with desired structure
```{r empty data.table}
dt_core <- data.table(c(NA), c(NA), c(NA), c(NA))
colnames(dt_core) <- c("accession", "Correct_species", "Correct_higher", "Incorrect")
```

Function to group the counts
```{r group counts function}
group_compute <- function(viral_seq, dt_core){
  counts <- fread(input = paste0(path_output, viral_seq, "/",
                                 viral_seq,
                                 "_Correct_Incorrect.tsv"))
  grouped <- counts[, .(total = sum(V1)), by = V6]
  grouped <- dcast(melt(grouped, id.vars = "V6"), variable ~ V6)
  grouped[, variable := NULL]
  grouped[, accession := viral_seq]
  
  if (!("Unclassified" %in% colnames(grouped))) {
    merged <- merge(dt_core, grouped, all = T, 
                    by = colnames(grouped))
  } else {
    merged <- rbind(dt_core, list(accession = viral_seq, 
                                  Correct_species = 0, 
                                  Correct_higher = 0, 
                                  Incorrect = 0))
  }
  
  return(merged)
}
```

Run for all
```{r group all}
#for (i in viral_sequences) {
for (i in rna_sequences) {
  dt_core <- group_compute(viral_seq = i, dt_core = dt_core)
}
```

Compute proportions
```{r proportions}
# Remove first row and change NAs to 0
dt_core <- dt_core[-1]
dt_core[is.na(dt_core)] <- 0

# Add total number of reads
#dt_simreads <- simulated_reads[V1 %in% viral_sequences, ]
dt_simreads <- simulated_reads[V1 %in% rna_sequences, ]
colnames(dt_simreads) <- c("accession", "total_reads")

dt_core <- merge(dt_core, dt_simreads, by = "accession")

# Proportions
dt_core[, prop_correct_sp := (Correct_species * 100)/total_reads]
dt_core[, prop_correct_ht := (Correct_higher * 100)/total_reads]
dt_core[, prop_incorrect := (Incorrect * 100)/total_reads]

dt_core[, unclassified := total_reads - (Correct_species + Correct_higher + Incorrect)]
dt_core[, prop_unclassified := (unclassified * 100/total_reads)]

dt_core[,.(mean(prop_correct_sp), mean(prop_correct_ht), mean(prop_incorrect),
           mean(prop_unclassified))]
```

