# config file to run "get_tables.smk"
script_Classifier_comparison: '/scratch/wally/FAC/FBM/DBC/amalaspi/virome/yarizmen/simulations_classifiers/Classifier_comparison_mean_of_means.R'

classifiers_R: "\"c(\\\"Centrifuge\\\", \\\"Kraken2\\\", \\\"DIAMOND\\\", \\\"MetaPhlAn2\\\")\""

classifiers: ['Centrifuge', 'Kraken2', 'DIAMOND', 'MetaPhlAn2']
#path2data: 'length_'

condition: 'length'

condition_values: [30, 40, 50, 60, 90, 120, 150]