---
title: "human reads"
output: html_notebook
---

## get data
```{r}

## 1. Number of counts (how many reads were assigned to “x” taxa)
## 2. taxID
## 3. taxID (as a double-check and because some taxIDs are deprecated)
## 4. Taxa name
## 5. Taxa rank
## 6. Classification: is it correct at species, correct at higher or incorrect?
## 7. How many taxa far away from the correct one? If it’s correct at species level this number is 0, and if it’s incorrect it is also 0.


library(data.table)
library(ggplot2)


classifiers <- c("Centrifuge", "Kraken2", "DIAMOND", "MetaPhlAn2")
cur.length <- 60

## read the files
data <-NULL
for(i in classifiers){
  files <- list.files(paste0("/Users/sneuensc/Sapfo/virome_yami/length/length_", cur.length, "/", i))
  for(f in files){
    tmp <- fread(paste0("/Users/sneuensc/Sapfo/virome_yami/length/length_", cur.length, "/", i, "/", f))
    tmp$classifier <- i
    tmp$original <- gsub("_Correct_Incorrect.tsv","", f)
    data <- rbind(data, tmp)
  }
}
colnames(data) <-c('reads','taxID','taxID2','taxName','rank','classification','rankLevel','classifier','original' )
data$classifier <- factor(data$classifier, levels=classifiers)

```

```{r}
data[, list('N' = .N), by=c('classifier','classification')]


d <- data[data$classification == "Incorrect", list('reads' = sum(reads), N = .N), by = c('classifier', 'original')]

ggplot(d, aes(x = reads, y = N)) +
  geom_point() +
  xlab("total number of incorrectly classifed reads") +
  ylab("number of extra taxa") +
  theme_classic() +
  ggtitle("Relationship between number of incorrectly classfied reads and number of extra taxa") +
  facet_wrap(~classifier, scales = "free") 

file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_incorrect_nb_reads_vs_nb_taxa.pdf"
ggsave(file, width = 297, height = 210*3/3, scale=1.5, units = "mm")
```


```{r}
data[,list(NN = .N), by='classifier'] 
  

ggplot(d, aes(x = original, y = N)) +
  geom_bar(stat="identity") +
  xlab("number of reads per extra taxa") +
  ylab("frequency in counts") +
  theme_classic() +
  ggtitle("Relationship between number of incorrectly classfied reads and number of extra taxa") +
  facet_wrap(~classifier, scales = "free") 



```


## extra taxa of incorrect classifications
```{r}


d <- data[data$classification == 'Incorrect',][,list('reads' = sum(reads)), by = c('taxID', 'taxName', 'classifier')]

FUN <- function(x) {
  if(length(x) <= 2) return(paste(x, collapse=" / "))
  return("")
}

dd <- d[,list('freq' = .N, 'taxID' = FUN(taxName)), by = c('reads', 'classifier')]
dd$reads <- factor(dd$reads, levels = sort(unique(dd$reads)))

max <- dd[,list(max = max(freq)), by = 'classifier']

nn <- merge(d[,list(reads = sum(reads), extra.taxa = .N), by = 'classifier'],
            max)

dd <- merge(dd, max)

ggplot(dd, aes(x = reads, y = freq)) +
  geom_bar(stat="identity") +
  xlab("number of reads per extra taxa") +
  ylab("frequency in counts") +
  theme_classic() +
  ggtitle("Extra taxa of incorrectly classfied reads") +
  geom_text(aes(x = reads, y = max/100 + freq, label = taxID), hjust = 0, vjust = 0.5, size = 2.5) +
  geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(reads, "incorrectly classified reads")), hjust = 0, vjust = 3) +
  geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(extra.taxa, "extra taxa")), hjust = 0, vjust = 5) +
  facet_wrap(~classifier, scales = "free") +
  coord_flip() 

file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_human_sims_incorrect.pdf"
##ggsave(file, width = 297, height = 210*3/3, scale=1.5, units = "mm")

```

## venn diagram of shared extra taxa
```{r}


d <- data[data$classification == 'Incorrect',][,list('reads' = sum(reads)), by = c('taxID', 'taxID', 'classifier')]

dd <- as.data.frame(dcast(d, taxID ~classifier, value.var = 'reads', fill=0))
rownames(dd)<-dd$taxName
dd <- as.matrix(dd[,-1])

ddd <- dd
ddd[ddd>0] <- 1

ee <- data.table(ddd)[,list('count' = .N), by=classifiers]

library(VennDiagram)

file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_human_venn_diagram.png"
venn.diagram(list("Centrifuge" = d$taxID[d$classifier == 'Centrifuge' ],
                  "Kraken2" = d$taxID[d$classifier == 'Kraken2' ],
                  "DIAMOND" = d$taxID[d$classifier == 'DIAMOND' ],
                  "MetaPhlAn2" = d$taxID[d$classifier == 'MetaPhlAn2']), 
             file = file, output = T,
             main = "Common extra taxa")
```

## get taxonomic tree
```{r}
library(taxonomizr)
## get db
path <- "/Users/sneuensc/Documents/Vital-IT/Sapfo/australia/NC_001422_sim_reads/"
getNamesAndNodes(path)                    # Function to download names.dmp and nodes.dmp from NCBI

# Create the sql databases
read.nodes.sql(paste0(path, 'nodes.dmp'), sqlFile = paste0(path, "nameNode.sqlite"), overwrite = FALSE) # First, add the nodes file
read.names.sql(paste0(path, 'names.dmp'), sqlFile = paste0(path, "nameNode.sqlite"), overwrite = FALSE)	# Secondly, add the names file


taxRanks<-as.data.frame(matrix(c("R", "root", 9,
                   "SK", "superkingdom", 8,
                   "K", "kingdom", 7,
                   "P", "phylum", 6,
                   "C", "class", 5,
                   "O", "order", 4,
                   "F", "family", 3,
                   "G", "genus", 2,
                   "S", "species", 1), byrow=T, ncol=3))
colnames(taxRanks) <- c("abrev","rank","rank.idx")


## get the classification
d3 <- data[, c(1,2,4,5,6,7,8,9)][ ,lapply(.SD, head, 1), by = c('taxID', 'taxName', 'original','classifier')]
d3 <- cbind(d3, getTaxonomy(ids = d3$taxID, sqlFile = paste0(path, "nameNode.sqlite"), desiredTaxa = taxRanks$rank))

## get the classification of the correct species
orig <- data[data$classification == "Correct_species", c(2,4,9)][ , lapply(.SD, head, 1), by = 'original']
orig <- cbind(orig, getTaxonomy(ids = orig$taxID, sqlFile = paste0(path, "nameNode.sqlite"), desiredTaxa = taxRanks$rank))
colnames(orig)[-1] <- paste0(colnames(orig)[-1], "_orig") 


## merge
d3 <- merge(d3, orig, by = 'original')


## get the MRCA
FUN <- function(x){
  nb <- length(x)/2
  x <- rev(x)
  for(i in nb:1){
    if(is.na(x[i]) & is.na(x[i + nb])) next
    if(is.na(x[i]) & !is.na(x[i + nb])) break
    if(!is.na(x[i]) & is.na(x[i + nb])) break
    if(x[i] != x[i + nb]) break
  }
  if(x[i] == x[i + nb]) return(i)
  return(i+1)
}
FUN <- function(x){
  nb <- length(x)/2
  x <- rev(x)
  a <- x[1:(nb)] == x[-(1:(nb))]
  for(i in length(a)){
    if(is.na(a[i])) next
    if(a[i] == T) return (i)
  }
  return(0)
}

lastNotNa1 <- function(x){
  x <- rev(x)
  for(i in 1:length(x)){
    if(!is.na(x[i])) return (i)
  }
  return(NaN)
}
d3$mrca <- apply(d3[,c(taxRanks$rank, paste0(taxRanks$rank, "_orig")), with = F], 1, FUN)
d3$rankLevel2 <- apply(d3[,c(taxRanks$rank, paste0(taxRanks$rank, "_orig")), with = F], 1, lastNotNa1)

d4 <- d3[, c('reads','taxID','taxName','rank','rankLevel','classification','classifier','original','mrca', taxRanks$rank), with = F]
tmp <- data[data$classification == "Correct_species", -c(3)]
tmp$mrca <- 1

d4 <- rbind(d4, tmp)

table(d4$mrca[d4$classification == "Correct_species"])
table(d4$mrca[d4$classification == "Correct_higher"])
table(d4$mrca[d4$classification == "Incorrect"])


d5 <- d4[,list("N" = .N, 'sum' = sum(reads), 'mean' = mean(reads)), 
         by = c('classifier', 'classification','mrca')]
d5 <- d5[d5$classification != "Unclassified",]
d5$N2 <- d5$N
d5$N2[d5$classification != "Correct_species"] <- NaN 
d5$mrca2 <- factor(rev(taxRanks$rank)[d5$mrca], levels = rev(taxRanks$rank))
d5$classification <- factor(d5$classification, levels = c('Correct_species','Correct_higher','Incorrect'))

colorcillos <- c(rgb(0, 158, 115, maxColorValue = 255),
                   rgb(181, 230, 0, maxColorValue = 255),
                   rgb(243, 155, 0, maxColorValue = 255),
                   rgb(213, 213, 213, maxColorValue = 255))

d6 <- d5
d6$classification2 <- as.character(d6$classification)
d6$classification2[d6$classification == 'Correct_species'] <- "Correct_species & Correct_higher"
d6$classification2[d6$classification == 'Correct_higher'] <- "Correct_species & Correct_higher"
d6$classification2 <- factor(d6$classification2, levels = c('Correct_species & Correct_higher', 'Incorrect'))

max.y <- d6[,list("max.y" = max(N)), by = c('classification2')]
max.x <- d6[,list("max.x" = .N), by = c('classifier')]

nn <- d6[,list("sum" = sum(N)), by = c('classifier','classification')]
nn$classification2 <- as.character(nn$classification)
nn$classification2[nn$classification == 'Correct_species'] <- "Correct_species & Correct_higher"
nn$classification2[nn$classification == 'Correct_higher'] <- "Correct_species & Correct_higher"
nn$classification2 <- factor(nn$classification2, levels = c('Correct_species & Correct_higher', 'Incorrect'))
nn <- merge(nn, max.y)
nn <- merge(nn, max.x, by = 'classifier')
nn.correct <- nn[nn$classification == 'Correct_species',]
nn <- nn[nn$classification != 'Correct_species',]
nn$color[nn$classification == 'Correct_higher'] <- colorcillos[2]
nn$color[nn$classification == 'Incorrect'] <- colorcillos[3]


d6 <- merge(d6, max.y)
d6$N.text <- d6$max.y/100 
d6$N.text[d6$N < d6$max.y/10] <- d6$N.text[d6$N < d6$max.y/10] + d6$N[d6$N < d6$max.y/10]



ggplot(d6, aes(x = mrca2, y = N, fill = classification)) +
  geom_bar(stat="identity") +
  xlab("first common taxonomic node ('MRCA')") +
  ylab("frequency in counts") +
  theme_classic() +
  scale_fill_manual(values = colorcillos) +
  geom_text(aes(x = mrca2, y = N.text, label = paste0(N, " (", round(mean), ")")), 
            hjust = 0, vjust = 0.5, angle = 90) +
  geom_text(aes(x = mrca2, y = N2, label = paste(N2, "taxas")), 
            color = colorcillos[1], size = 5, fontface = 2, hjust = 0.2, vjust = -0.2) +
  geom_text(data = nn, aes(x = max.x/2.5, y = max.y/(2), label = paste(sum, "taxas")), 
            color = nn$color, size = 5, fontface = 2) +
  facet_grid(vars(classification2), vars(classifier), scales = "free") +
  ggtitle("common taxonomic node") +
  theme(legend.position=c(0.93, 0.93)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) 

file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_length_60bp_common_taxonomic_node.pdf"
ggsave(file, width = 297, height = 210*3/3, scale=1.5, units = "mm")
```


## get taxonomic tree II
```{r}
library(taxonomizr)
## get db
path <- "/Users/sneuensc/Documents/Vital-IT/Sapfo/australia/NC_001422_sim_reads/"
getNamesAndNodes(path)                    # Function to download names.dmp and nodes.dmp from NCBI

# Create the sql databases
read.nodes.sql(paste0(path, 'nodes.dmp'), sqlFile = paste0(path, "nameNode.sqlite"), overwrite = FALSE) # First, add the nodes file
read.names.sql(paste0(path, 'names.dmp'), sqlFile = paste0(path, "nameNode.sqlite"), overwrite = FALSE)	# Secondly, add the names file


taxRanks<-as.data.frame(matrix(c("D", "domain",
                   "SK", "superkingdom",
                   "K", "kingdom",
                   "P", "phylum",
                   "C", "class",
                   "O", "order",
                   "F", "family",
                   "G", "genus",
                   "S", "species"), byrow=T, ncol=2))
colnames(taxRanks) <- c("abrev","rank")


## get the classification
d3 <- data[data$classification != "Correct_species", c(1,2,4,5,6,8,9)][ ,lapply(.SD, head, 1), by = c('taxID', 'taxName', 'original','classifier')]
d3 <- cbind(d3, getTaxonomy(ids = d3$taxID, sqlFile = paste0(path, "nameNode.sqlite"), desiredTaxa = taxRanks$rank))

## get the classification of the correct species
orig <- data[data$classification == "Correct_species", c(2,4,9)][ , lapply(.SD, head, 1), by = 'original']
orig <- cbind(orig, getTaxonomy(ids = orig$taxID, sqlFile = paste0(path, "nameNode.sqlite"), desiredTaxa = taxRanks$rank))
colnames(orig)[-1] <- paste0(colnames(orig)[-1], "_orig") 


## merge
d3 <- merge(d3, orig, by = 'original')
d3 <- d3[,c(1:7, 17:18, 8:16, 19:27)]


## get the MRCA
FUN <- function(x){
  nb <- length(x)/2
  x <- rev(x)
  for(i in nb:1){
    if(is.na(x[i]) & is.na(x[i + nb])) next
    if(is.na(x[i]) & !is.na(x[i + nb])) break
    if(!is.na(x[i]) & is.na(x[i + nb])) break
    if(x[i] != x[i + nb]) break
  }
  return(i+1)
}
FUN2 <- function(x){
  nb <- length(x)/2
  x <- rev(x)
  for(i in nb:1){
    if(is.na(x[i]) & is.na(x[i + nb])) next
    if(is.na(x[i]) & !is.na(x[i + nb])) break
    if(!is.na(x[i]) & is.na(x[i + nb])) break
    if(x[i] != x[i + nb]) break
  }
  return(x[i + nb])
}
d3$mrca <- apply(d3[,-(1:9)], 1, FUN)
d3$otherTaxa <- apply(d3[,-c(1:9, ncol(d3)), with = F], 1, FUN2)

d3$mrca[d3$taxName == "root"] <- 10

d4 <- d3[, c('reads','taxID','taxName','rank','classification','classifier','original','mrca','otherTaxa')]
tmp <- data[data$classification == "Correct_species", -c(3,7)]
tmp$mrca <- 1
tmp$otherTaxa <- ""

d4 <- rbind(d4, tmp)

table(d4$mrca[d4$classification == "Correct_species"])
table(d4$mrca[d4$classification == "Correct_higher"])
table(d4$mrca[d4$classification == "Incorrect"])


d5 <- d4[,list("N" = .N, 'sum' = sum(reads), 'mean' = median(reads)), 
         by = c('classifier', 'classification','mrca','otherTaxa')]
d5 <- d5[d5$classification != "Unclassified",]
d5$mrca2 <- factor(rev(c("root", taxRanks$rank))[d5$mrca], levels = rev(c("root", taxRanks$rank)))
d5$classification <- factor(d5$classification, levels = c('Correct_species','Correct_higher','Incorrect'))

colorcillos <- c(rgb(0, 158, 115, maxColorValue = 255),
                   rgb(181, 230, 0, maxColorValue = 255),
                   rgb(243, 155, 0, maxColorValue = 255),
                   rgb(213, 213, 213, maxColorValue = 255))


d6 <- d5
d6$classification2 <- as.character(d6$classification)
d6$classification2[d6$classification == 'Correct_species'] <- "Correct_species & Correct_higher"
d6$classification2[d6$classification == 'Correct_higher'] <- "Correct_species & Correct_higher"
d6$classification2 <- factor(d6$classification2, levels = c('Correct_species & Correct_higher', 'Incorrect'))

max.y <- d6[,list("max.y" = max(N)), by = c('classification')]
max.x <- d6[,list("max.x" = .N), by = c('classifier')]
nn <- d6[,list("sum" = sum(N)), by = c('classifier','classification')]
nn <- merge(nn, max.y)
nn <- merge(nn, max.x, by = 'classifier')

d6 <- merge(d6, max.y)
d6$N.text <- d6$N
d6$N.text[d6$N > d6$max.y/2] <- d6$max.y/2 




d7 <- d6[d6$classification=="Incorrect" & d6$classifier == "Centrifuge",]
ggplot(d6, aes(x = mrca2, y = N, fill = otherTaxa)) +
  geom_bar(stat="identity") +
  xlab("first common taxonomic node ('MRCA')") +
  ylab("frequency in counts") +
  theme_classic() +
  theme(legend.position = "none") +
  #scale_fill_manual(values = colorcillos) +
  #geom_text(aes(x = mrca2, y = N.text, label = paste0(N, " (", round(mean), ")", collapse = " / ")), hjust = 0, vjust = 0.5, angle = 90) +
  #geom_text(aes(x = mrca2, y = max/100 + N, label = N), hjust = 0, vjust = 0.5, size = 3) +
  #geom_text(data = nn, aes(x = max.x/2, y = max.y/(2), 
  #                           label = paste(sum, "taxas"))) +
  facet_grid(vars(classification2), vars(classifier), scales = "free") +
  ggtitle("common taxonomic node") 

file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_length_60bp_common_taxonomic_node2.pdf"
ggsave(file, width = 297, height = 210*3/3, scale=1.5, units = "mm")

```

```{r}





## number of not found taxaIDs 
d3[,list('N.NAs' = sum(is.na(species)), 'N' = .N), by='classifier']

FUN <- function(x){
  for(i in length(x):1){
    if(!is.na(x[i])) return(i)
    }
  return(NaN)
}
d3$rank <- apply(d3[,-(1:5)], 1, FUN)
d3[is.na(d3$rank)]

hist(d3$rank)

d4 <- d3[,list(N = .N), by = c('rank','classifier')]
d4$rank2 <- taxRanks$rank[d4$rank+1]
d4$rank2[is.na(d4$rank2)] <- "NA"
d4$rank2 <- factor(d4$rank2, levels=c("NA", taxRanks$rank))

maxx <- d4[,list(max = sum(N), NN = .N), by = 'classifier']
d4 <- merge(d4, maxx)
d4$max2[is.na(d4$rank)] <- d4$max[is.na(d4$rank)]


ggplot(d4, aes(x = rank2, y = N)) +
  geom_bar(stat="identity") +
   xlab("taxonomic rank") +
  ylab("frequency in counts") +
  theme_classic() +
  ggtitle("Taxonomic rank of classifed reads") +
  geom_text(aes(x = rank2, y = max/100 + N, label = paste0(N, " (", round(100*N/max,1), "%)")), 
            hjust = 0, vjust = 0.5, size = 3) +
  geom_text(data = maxx, aes(x = NN/2, y = max, 
                             label = paste(max, "different taxas in total")), hjust = 1, vjust = 3) +
   facet_wrap(~classifier, scales = "free") +
  coord_flip() 

file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_human_sims_taxRanks.pdf"
ggsave(file, width = 297, height = 210*2/3, scale=1.5, units = "mm")

```

```{r}



library("ggVennDiagram")
for(rank in taxRanks$rank){
  #rank <- "order"  
  
  d <- d3
  d$cur.rank <- d[,rank, with =F]
  d <- d[,list(reads = sum(reads), N = .N), by = c('cur.rank', 'classifier')]
  
  d <- d[! is.na(d$cur.rank),]
  
  l <- list("Centrifuge" = d$cur.rank[d$classifier == 'Centrifuge' ],
            "Kraken2" = d$cur.rank[d$classifier == 'Kraken2' ],
            "DIAMOND" = d$cur.rank[d$classifier == 'DIAMOND' ],
            "MetaPhlAn2" = d$cur.rank[d$classifier == 'MetaPhlAn2'])
  
  
  ggVennDiagram(l, label_alpha = 0) +
    ggtitle(paste("Common extra taxa at the", rank, "level")) +
    theme(legend.position = "none")
  
  file <- paste0("/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_human_venn_diagram_", rank, ".pdf")
  ggsave(file, width = 210, height = 210, scale=1.5, units = "mm")
}
```


```{r}

## sort
d <- d[order(d$classifier, d$reads, decreasing = T),]

## get x most hit taxa per classifier
dd <- d[ ,.SD[1:10], by = 'classifier']

#dd$reads <- factor(dd$reads, levels = sort(unique(dd$reads, decreasing = T)))

## hack to ge the rigth ordering
dd$order <- paste0("A", 1: nrow(dd))
dd$order <- factor(dd$order, levels = rev(dd$order))



ggplot(dd, aes(x = order, y = reads)) +
  geom_bar(stat="identity") +
  xlab("") +
  ylab("# reads") +
  theme_classic() +
  ggtitle(paste("Extra taxa of incorrectly classfied reads at the", rank, "level")) +
  #geom_text(aes(x = reads, y = max/100 + freq, label = taxID), hjust = 0, vjust = 0.5, size = 2.5) +
 # geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(reads, "incorrectly classified reads")), hjust = 0, vjust = 3) +
  #geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(extra.taxa, "extra taxa")), hjust = 0, vjust = 5) +
  facet_wrap(~classifier, scales = "free") +
  
  scale_x_discrete("name", breaks = 1:nrow(dd), labels = dd$cur.rank) +
  coord_flip() 
```


```{r}







dd <- d[,list('freq' = .N, 'taxID' = FUN(cur.rank)), by = c('cur.rank', 'classifier')]
dd$reads <- factor(dd$reads, levels = sort(unique(dd$reads)))

max <- dd[,list(max = max(freq)), by = 'classifier']

nn <- merge(d[,list(reads = sum(reads), extra.taxa = .N), by = 'classifier'],
            max)

dd <- merge(dd, max)

ggplot(dd, aes(x = reads, y = freq)) +
  geom_bar(stat="identity") +
  xlab("number of reads per extra taxa") +
  ylab("frequency in counts") +
  theme_classic() +
  ggtitle(paste("Extra taxa of incorrectly classfied reads at the", rank, "level")) +
  geom_text(aes(x = reads, y = max/100 + freq, label = taxID), hjust = 0, vjust = 0.5, size = 2.5) +
  geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(reads, "incorrectly classified reads")), hjust = 0, vjust = 3) +
  geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(extra.taxa, "extra taxa")), hjust = 0, vjust = 5) +
  facet_wrap(~classifier, scales = "free") +
  coord_flip() 

file <- paste0("/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_human_sims_incorrect_", rank, ".pdf")
ggsave(file, width = 297, height = 210*3/3, scale=1.5, units = "mm")
}
```





