---
title: "figure_09_human_sims_taxRanks"
output: html_notebook
---

## get data
```{r}

## 1. Number of counts (how many reads were assigned to “x” taxa)
## 2. taxID
## 3. taxID (as a double-check and because some taxIDs are deprecated)
## 4. Taxa name
## 5. Taxa rank
## 6. Classification: is it correct at species, correct at higher or incorrect?
## 7. How many taxa far away from the correct one? If it’s correct at species level this number is 0, and if it’s incorrect it is also 0.



library(data.table)
library(ggplot2)


classifiers <- c("Centrifuge", "Kraken2", "DIAMOND", "MetaPhlAn2")
folder <- "/Users/sneuensc/Sapfo/virome_yami/analyses_review"
sqlFile='accessionTaxa.sql'


## read the raw files
data <-NULL
for(i in classifiers){
  print(i)
  tmp <- fread(paste0(folder, "/human_sims/", i, "_human_sims_count_table.tsv"))
  if(i=="MALT"){
    tmp <- tmp[,2:1]
    colnames(tmp) <- c("V1", "V2")
  }
  tmp$Classifier <- i
  data <- rbind(data, tmp)
}
data <- data[data$V2>0,] ## remove 0 and -2 taxID (i.e., unclassified)
colnames(data) <-c('reads','taxID','Classifier')
data$Classifier <- factor(data$Classifier, levels=classifiers)

## get classification
true.taxa <- read.table(paste0(folder,"/human_sims/9606_taxIDs.txt"), sep="\t")$V1

## add the total number of reads
reads.tot <-476876980

data$classification[data$taxID %in% true.taxa[-1]] <- "Correct_higher"
data$classification[data$taxID %in% true.taxa[1]] <- "Correct_species"
data$classification[!data$taxID %in% true.taxa] <- "Incorrect"

## add the number of unclassified
dd <- data[,list('reads' = reads.tot - sum(reads)), by = 'Classifier']
dd$classification <- "Unclassified"
dd$taxID = "NaN"
dd <- dd[,c('reads','taxID','Classifier','classification')]
data <- rbind(data, dd)

data$classification <- factor(data$classification, levels = c('Correct_species','Correct_higher','Incorrect','Unclassified'))

## replace missing values with 0
for(c in unique(data$classification)){
  for(l in unique(data$Classifier)){
    if(length(data$reads[data$classification == c & data$Classifier == l]) == 0){
      data <- rbind(data, list('reads' = 0, 'taxID' = NaN, 'Classifier' = l, 'classification' = c))
    }
  }
}


dataHuman <- data
```




## get taxonomic tree
```{r}
library(taxonomizr)
library(dplyr)
library(RColorBrewer)

data <-dataHuman

## read the db
nodes <- fread(paste0(folder, "/nodes.dmp"), sep="|")

taxRanks<-as.data.frame(matrix(c("SK", "superkingdom",
                                 "K", "kingdom",
                                 "P", "phylum",
                                 "C", "class",
                                 "O", "order",
                                 "F", "family",
                                 "G", "genus",
                                 "S", "species"), byrow=T, ncol=2))
colnames(taxRanks) <- c("abrev","rank")

d3 <- data[data$classification == 'Incorrect'][,list('reads' = sum(reads)), by = c('taxID', 'Classifier')]

## get the classification
d3 <- cbind(d3, getTaxonomy(ids = d3$taxID, sqlFile = paste0(folder,"/",sqlFile), desiredTaxa = taxRanks$rank))

## add missing taxa
d3[d3$taxID==697227]$superkingdom <- "Viruses"
d3[d3$taxID==697227]$kingdom <- "Heunggongvirae"
d3[d3$taxID==39113]$superkingdom <- "Viruses"
d3[d3$taxID==39113]$kingdom <- "Orthornavirae"
d3[d3$taxID==1435497]$superkingdom <- "Viruses"
d3[d3$taxID==1435497]$kingdom <- "Shotokuvirae"

FUN <- function(x){
  for(i in length(x):1){
    if(!is.na(x[i])) return(i)
  }
  return(NaN)
}
d3$rank <- apply(d3[,taxRanks$rank, with=F], 1, FUN)
#d3[is.na(d3$rank)]

col.taxa <- data.frame(superkingdom = c("Bacteria","Archaea","Viruses","Eukaryota","other"), 
                       color = c('#61D04F', '#DF536B', '#2297E6', '#28E2E5','black'))


d5 <- d3[,list(N = .N), by = c('Classifier','superkingdom','kingdom')]

curTaxa <- d3[,list(N = .N), by = c('superkingdom','kingdom')]
curTaxa$kingdom[is.na(curTaxa$kingdom)] <- "unkown" 
curTaxa$'superkingdom - kingdom' <-paste(curTaxa$superkingdom, "-", curTaxa$kingdom)
curTaxa$order[curTaxa$superkingdom == 'Viruses'] <- "3_Viruses"
curTaxa$order[curTaxa$superkingdom == 'Eukaryota'] <- "2_Eukaryota"
curTaxa$order[curTaxa$superkingdom == 'Bacteria'] <- "1_Bacteria"
curTaxa <- curTaxa[order(curTaxa$order, N, decreasing=T),]
curTaxa$order2 <- 1:nrow(curTaxa)

## color pallet
set.seed(7)
qual_col_pals <- brewer.pal.info[brewer.pal.info$category == 'qual', ]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
color <- data.table(`superkingdom - kingdom`= names(table(curTaxa$`superkingdom - kingdom`)),
                    color = sample(col_vector, length(table(curTaxa$`superkingdom - kingdom`))))
curTaxa <- merge(curTaxa, color, sort = F)

curTaxa$'superkingdom - kingdom' <- factor(curTaxa$'superkingdom - kingdom', levels = curTaxa$'superkingdom - kingdom')


my.pie <- NULL
for(c in classifiers){
  tmp <- d5[d5$Classifier == c,]
  tmp$kingdom[is.na(tmp$kingdom)] <- "unkown" 
  tmp <- merge(tmp, curTaxa[,c('superkingdom','kingdom','superkingdom - kingdom','order2','color')], by <- c('superkingdom','kingdom'), all.x=T)
  tmp <- tmp[order(tmp$order2),]
  
  my.pie[[c]] <- ggplot(tmp, aes(x = "", fill= `superkingdom - kingdom`, y = N)) +
    geom_bar(width = 1, stat = "identity", color = "white") +
    coord_polar("y", start = 0) +
    scale_fill_manual(values = tmp$color) +
    theme_void() +
    theme(legend.position = "none")
  
  
  ggsave(paste0(folder, "/figure_human_sims_taxRanks_",c,".pdf"), width = 85, height = 85, scale=0.7, units = "mm")
}
## get the legend ;-)
tmp <- curTaxa
ggplot(tmp, aes(x = "", fill= `superkingdom - kingdom`, y = N)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = tmp$color) +
  theme_void()
ggsave(paste0(folder, "/figure_human_sims_taxRanks_legend.pdf"), width = 90, height = 150, scale=0.7, units = "mm")

d4 <- d3[,list(N = .N), by = c('rank','Classifier')]
d4$rank2 <- taxRanks$rank[d4$rank]
d4$rank2[is.na(d4$rank2)] <- "NA"
d4$rank2 <- factor(d4$rank2, levels=c("NA", taxRanks$rank))

maxx <- d4[,list(max = sum(N), NN = .N), by = 'Classifier']
d4 <- merge(d4, maxx)
d4$max2[is.na(d4$rank)] <- d4$max[is.na(d4$rank)]


r <- ggplot(d4, aes(x = rank2, y = N)) +
  geom_bar(stat="identity") +
  xlab("taxonomic rank") +
  ylab("frequency in counts") +
  theme_classic() +
  #ylim(0,1246) +
  ggtitle("Taxonomic rank of classifed reads") +
  geom_text(aes(x = rank2, 
                y = ifelse(N > 2000, N - 2000, N + 70), 
                label = paste0(N, " (", round(100*N/max,1), "%)")),
            color = ifelse(d4$N > 2000, "white", "black"),
            hjust = 0, vjust = 0.5, size = 3) +
  # geom_text(data = maxx, aes(x = NN/2, y = 1250, 
  #                           label = paste(max, "different taxas in total")), hjust = 1, vjust = 3.5) +
  facet_wrap(~Classifier, scales = "free_y") +
  theme(legend.position = "none") +
  coord_flip() 
r
ggsave(paste0(folder,"/figure_09_human_sims_taxRanks.pdf"), width = 297*2/3, height = 210*2/3, scale=1, units = "mm")

```
