---
  title: "Classifier detailed"
  output: html_notebook
---
  



## detected virus (only at 1 read threshold)
```{r, eval=T}
## get data
plot.detected_viruses2 <- function(data, title, color1, thres){

  max.taxa <- data[,.N, by=Classifier]
  
  d1 <-NULL
  for(i in thres){
    FUN <- function(x)return(sum(x>i))
    tmp <- data[, list('pres' = FUN(Correct_Sp)), by = c('Classifier')]
    tmp$thres <- paste0(i, " reads")
    d1 <- rbind(d1, tmp)
  }
  d1$thres[d1$thres == "1 reads"] <- "1 read"
  
  d1$thres <- factor(d1$thres, levels = unique(d1$thres))
  #d1$classifier <- factor(d1$classifier, levels = levels(data$classifier))
  
  d1 <- merge(d1, max.taxa, all.x=T)
  
  o4a <- ggplot(d1, aes(x = Classifier, y = pres, fill = thres)) +
    geom_bar(stat="identity", position = "dodge") +
    scale_color_manual(values = colours) +
    theme_classic() +
    geom_hline(yintercept=max(max.taxa$N), linetype="dashed") +
    scale_fill_manual(values = color1) +
    #geom_vline(xintercept=unique(extra$length), color=gray(0.9)) +
    geom_text(aes(length(table(d1$Classifier))+0.5, max(max.taxa$N), 
                  label = paste(max(max.taxa$N),"simulated viral sequences"), vjust = -0.6, hjust = 1)) +
    #guides(color=guide_legend(title="Classifier")) +
    geom_text(aes(label = paste(pres, "/", N)), position=position_dodge(width=0.9), 
              vjust=1.5, hjust = 0.5, cex=3, color = "white") +
    ggtitle(title) +
    #guides(fill=guide_legend(title="Threshold")) +
    xlab("") +
    theme(legend.position = "none") +
    ylab("# viruses detected") #+
    #theme(legend.position = "none")
  o4a
}
library(colorspace)
plot.detected_viruses2(dataAll[dataAll$Idx=='length_60',c('Classifier','Correct_Sp')], 
                            "B. Total number of correctly detected viruses", 
                               colorcillos[1], 1)

```

## extra taxa 3 (only 1 read as threshold)
```{r}
plot.extra_taxa_mean3 <- function(extra, title, colors){
  
  d <- extra
  d$extra2 <- apply(d[,-1], 1, sum)
  
  d1 <- d[,list("extra"=mean(extra2, na.rm=T)), by=c('Classifier')]
  print(d1)

  ggplot(d1, aes(y=extra, x=Classifier)) + 
    geom_bar(position = "stack", stat = "identity", fill= "orange") + 
    ggtitle(title) +
    ylab("Mean number of extra taxa")  +
    xlab("")  +
    #scale_fill_manual(values = colors) +
    geom_text(aes(label = sprintf("%.2f", extra)), position=position_dodge(width=0.9), 
              vjust=1.5, hjust = 0.5, cex=3, color = "white") +
    theme_classic() 
    #theme(legend.position=c(0.85, 0.75))
    #theme(legend.position=c(0.2, 0.75))

}

library("RColorBrewer")
names <- paste0(rank.taxa, "_nb.taxa_1")
columns <- c("Classifier",names)
c04 <-plot.extra_taxa_mean3(dataAll[dataAll$Idx=='length_60', ..columns], 
                                   "C. Mean number of spurious extra taxa", 
                                   brewer.pal(n = length(rank.taxa), name = 'Set1'))
c04

```
## precision - sensitivity mean
```{r}
plot.sensitivity_precision2 <- function(d, title, colors){
  
  ## sensitivity
  d$sens <- d$`Correct species`/
    (d$`Correct species` + d$`Correct higher` + d$Unclassified + d$Incorrect)
  d$sens2 <- (d$`Correct species` + d$`Correct higher`) /
    (d$`Correct species` + d$`Correct higher` + d$Unclassified + d$Incorrect)

  ## precision
  d$prec <- d$`Correct species`/
    (d$`Correct species` + d$`Correct higher` + d$Incorrect)
  d$prec2 <- (d$`Correct species` + d$`Correct higher`) /
    (d$`Correct species` + d$`Correct higher` + d$Incorrect)

  e <- rbind(d[,list('Sensitivity' = 100*mean(sens), 
                      'Precision' = 100*mean(prec, na.rm=T), 'Category' = 'species'), 
                by = 'Classifier'],
             d[,list('Sensitivity' = 100*mean(sens2), 
                      'Precision' = 100*mean(prec2, na.rm=T), 'Category' = 'species & higher'),
                by=Classifier])
  print(e)

  e$x <- e$Sensitivity
  e$y <- e$Precision
  
  sel <- c('DIAMOND','MetaPhlAn2')
  e$x[e$Classifier %in% sel & e$Category == "species & higher"] <- 
    e$x[e$Classifier %in% sel & e$Category == "species & higher"] -23
  e$x[e$Classifier %in% sel & e$Category == "species"] <- 
    e$x[e$Classifier %in% sel & e$Category == "species"] -20
  
  sel <- c('MALT','Centrifuge','Kraken2')
  e$x[e$Classifier %in% sel] <-  e$x[e$Classifier %in% sel] +2.5
  
  sel <- 'Centrifuge'
  e$x[e$Classifier %in% sel & e$Category == "species"] <-  
    e$x[e$Classifier %in% sel  & e$Category == "species"] -22.5

  e$y[e$Classifier %in% 'Centrifuge' & e$Category == "species & higher"] <- 
    e$y[e$Classifier %in% 'Centrifuge' & e$Category == "species & higher"] -2  
  
  e$y[e$Classifier %in% 'Kraken2' & e$Category == "species & higher"] <- 
    e$y[e$Classifier %in% 'Kraken2' & e$Category == "species & higher"] +0

  e$y[e$Classifier %in% 'Kraken2' & e$Category == "species"] <- 
    e$y[e$Classifier %in% 'Kraken2' & e$Category == "species"] -8

    e$text <- ifelse(e$Category == "species", 
                                 paste0("Sensitivity_s: ", round(e$Sensitivity,1), 
                                        "%\nPrecision_s: ", round(e$Precision,1), "%"),
                                 paste0("Sensitivity_s&h: ", round(e$Sensitivity,1), 
                                        "%\nPrecision_s&h: ", round(e$Precision,1), "%"))

  ## set the position for the classifier names
  eee <- data.frame('Classifier' = e$Classifier[e$Category == "species"], 
                   'x' = (e$Sensitivity[e$Category == "species"] + e$Sensitivity[e$Category == "species & higher"]) / 2,
                   'y' = (e$Precision[e$Category == "species"] + e$Precision[e$Category == "species & higher"]) / 2,
                   'Category' = "species")
  eee$Classifier <- factor(eee$Classifier, levels = levels(e$Classifier))
  
  eee$x[eee$Classifier == "MetaPhlAn2"] <- eee$x[eee$Classifier == "MetaPhlAn2"] -15
  eee$x[eee$Classifier == "DIAMOND"] <- eee$x[eee$Classifier == "DIAMOND"] -10
  eee$x[eee$Classifier == "Centrifuge"] <- eee$x[eee$Classifier == "Centrifuge"] -15
  eee$x[eee$Classifier == "Kraken2"] <- eee$x[eee$Classifier == "Kraken2"] -7
  eee$y[eee$Classifier == "Kraken2"] <- 100
  
  
  p1 <- ggplot(e, aes(x = Sensitivity, y = Precision, color = Classifier, shape = Category)) +
    theme_classic() +
    geom_point(size = 7) +
    #ylab("Mean precision") +
    #ylim(40,100) +
#    geom_text(aes(x = x, y = y, label = text), hjust = 0, cex=3.5) +
    #geom_text(data = eee, aes(x = x, y = y, label = Classifier), size=8) +
    scale_color_manual(values = colors) +
    ggtitle(title) +
    guides(color=guide_legend(title="Classifier")) +
    scale_shape_discrete(name = "Considered correct", labels = c("species", "species & higher")) +

#    guides(color=F, shape=guide_legend(title="Considered correct")) +
    scale_x_continuous("Mean sensitivity", breaks = seq(0,100, 10), labels = seq(0,100, 10), limits = c(0, 100)) +     scale_y_continuous("Mean precision", breaks = seq(40,100, 10), labels = seq(40,100, 10), limits = c(40, 100)) +
    theme(legend.position=c(0.9, 0.32),
        panel.grid.major = element_line(),
        #legend.box = "horizontal",
        #plot.margin=unit(c(5.5, 110, 5.5, 5.5), "points")
        ) +
    coord_cartesian(clip = "off")
  
  p1 <- addSmallLegend(p1, pointSize = 3, textSize = 9, spaceLegend = 0.6)
  p1
  

}

a04 <- plot.sensitivity_precision2(
  dataAll[dataAll$Idx=='length_60',c('GenBankID','Classifier','Correct species','Correct higher','Unclassified','Incorrect')], 
  "A. Sensitivity vs. precision", color.classifers)
a04
```

## figure 03 length 60 details
```{r}
library("gridExtra")
library(colorspace)
library("RColorBrewer")

## remove not present viruses in DIAMOND
vir <- read.table("/Users/sneuensc/Documents/Vital-IT/Sapfo/virome_yami/analyses_review/present_viruses/viruses_not_present_DIAMOND_database_233_set")$V1
dataAll <- dataAll[!(dataAll$Classifier=="DIAMOND" & dataAll$GenBankID %in% vir),]

## remove not present viruses in MetaPhlAn2
vir <- read.table("/Users/sneuensc/Documents/Vital-IT/Sapfo/virome_yami/analyses_review/present_viruses/viruses_not_present_in_MPA2_database_233_set")$V1
dataAll <- dataAll[!(dataAll$Classifier=="MetaPhlAn2" & dataAll$GenBankID %in% vir),]

a04 <- plot.sensitivity_precision2(
  dataAll[dataAll$Idx=='length_60',c('GenBankID','Classifier','Correct species','Correct higher','Unclassified','Incorrect')], 
  "A. Sensitivity vs. precision", color.classifers)

b04 <-plot.detected_viruses2(dataAll[dataAll$Idx=='length_60',c('Classifier','Correct_Sp')], 
                            "B. Total number of correctly detected viruses", 
                               colorcillos[1], 1)

names <- paste0(rank.taxa, "_nb.taxa_1")
columns <- c("Classifier",names)
c04 <-plot.extra_taxa_mean3(dataAll[dataAll$Idx=='length_60', ..columns], 
                                   "C. Mean number of spurious extra taxa", 
                                   brewer.pal(n = length(rank.taxa), name = 'Set1'))


lay <- rbind(c(1,1),c(2,3))
grob <- grid.arrange(grobs=list(a04, b04, c04), layout_matrix=lay)   
ggsave(paste0(folder,"/figure_04_length_60_details_onlyPresentViruses.pdf"), width = 297, height = 297, scale=0.8, units = "mm", grob)


```


