---
  title: "Figure S06 MALT"
  output: html_notebook
---


## classification per virus
```{r}
plot.classification_per_virus <- function(mmm, title, xlab, colors){
  library(data.table)
  library(ggplot2)
  library(reshape2)
  
  ## ordering following correct species
  mmm <- mmm[order(mmm$`Correct species`, mmm$`Correct higher`, mmm$Unclassified, mmm$Incorrect, decreasing = T),]
  
  
  
  data <- data.table(reshape2::melt(mmm, id.vars = c('Classifier','GenBankID')))
  colnames(data)[3:4] <- c("category", "props")
  
  d <- NULL
  for(i in levels(data$Classifier)){
    sel = data[data$Classifier == i,]
    tmp <- sel[sel$category == "Correct species", ]
    #tmp <- tmp[order(tmp$props, tmp$category, decreasing = T),]
    ord <- data.frame('GenBankID' = tmp$GenBankID, 'order' = 1:nrow(tmp))
    
    d <- rbind(d, merge(sel, ord))
  }
  
  d$class <- "correct species"
  dd <- d
  
  
  ## ordering following correct species & hihger
  mmm$correct2 <- mmm$`Correct species` + mmm$`Correct higher`
  mmm <- mmm[order(mmm$correct2, mmm$`Correct species`, mmm$`Correct higher`, mmm$Unclassified, mmm$Incorrect, decreasing = T),]
  mmm <- mmm[, -7]
  
  ## 
  data <- data.table(reshape2::melt(mmm, id.vars = c('Classifier','GenBankID')))
  colnames(data)[3:4] <- c("category", "props")
  
  ## correct species & higher
  d <- NULL
  for(i in levels(data$Classifier)){
    sel = data[data$Classifier == i,]
    tmp <- sel[sel$category == "Correct species", ]
    tmp$props2 <- sel$props[sel$category == "Correct higher"]
    #tmp <- tmp[order(tmp$props + tmp$props2, decreasing = T),]
    ord <- data.frame('GenBankID' = tmp$GenBankID, 'order' = 1:nrow(tmp))
    
    d <- rbind(d, merge(sel, ord))
  }
  
  d$class <- "correct species & higher"
  dd <- rbind(dd, d)
  dd$class <- factor(dd$class, levels = c("correct species", "correct species & higher"))
  
  dd$order <- factor(dd$order, levels=1:max(dd$order))
  dd$category <- factor(dd$category, levels=rev(c("Correct species","Correct higher","Incorrect","Unclassified")))
  
  dd$props[dd$props==0] <- NaN
  
  d1 <- ggplot(dd, aes(color = category, fill = category, x = order, y = props)) +
    theme_classic() +
    geom_bar(stat="identity") +
    scale_fill_manual(values = rev(colors)) +
    scale_color_manual(values = rev(colors)) +
    ylab("% reads") +
    xlab(xlab) +
    ggtitle(title) +
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          legend.position = "none") +
    facet_grid(vars(Classifier), vars(class))
  d1
}

aS02 <- plot.classification_per_virus(
  dataAll[dataAll$Idx=='length_60',c('GenBankID','Classifier','Correct species','Correct higher','Unclassified','Incorrect')], 
  #  'A. Classification per virus', "viruses (order vary per classifier)", colorcillos)
  'A. Classification per virus', "viruses (order vary per subfigure)", colorcillos)
aS02

```

## classification mean
```{r}
plot.classification_mean <- function(mmm, title, colors){
  
  data <- data.table(reshape2::melt(mmm, id.vars = c('Classifier','GenBankID')))
  colnames(data)[3:4] <- c("category", "props")
  
  ################################################################################################
  ## mean categories
  data$category <- factor(data$category, levels=c("Correct species","Correct higher","Incorrect","Unclassified"))
  
  d <- data.table(data)[,list(props = mean(props)), by = c('category','Classifier')]
  a1 <- ggplot(d, aes(y = props, fill = category, x = Classifier)) +
    geom_bar(stat="identity", position="dodge") +
    scale_fill_manual(values = colors) +
    scale_color_manual(values = colors) +
    geom_text(aes(label = sprintf("%.2f", props)), 
              position=position_dodge(width=0.9), hjust=-0.1, cex = 3, angle = 90) +
    ylab("% reads") +
    xlab("") +
    ylim(0,100) +
    ggtitle(title) +
    guides(fill=guide_legend(title="Classification")) +
    theme_classic() +
    theme(legend.position=c(0.74, 0.6),
          #theme(legend.position=c(0.74, 0.78),
          panel.grid.major.y = element_line())
  
  a1
}

bS02 <- plot.classification_mean(dataAll[dataAll$Idx=='length_60',c('GenBankID','Classifier','Correct species','Correct higher','Unclassified','Incorrect')], 
                                 'B. Mean classification', colorcillos)
bS02
```

## figure S02 length_60_sup
```{r}
library(gridExtra)
lay <- rbind(c(1,2))
grob <- grid.arrange(grobs=list(aS02, bS02), layout_matrix=lay)   
ggsave(paste0(folder,"/figure_S06_MALT.pdf"), 
       width = 297, height = 210*2/3, scale=0.9, units = "mm", grob)

```



