---
title: "human reads"
output: html_notebook
---

## get data
```{r}

## 1. Number of counts (how many reads were assigned to “x” taxa)
## 2. taxID
## 3. taxID (as a double-check and because some taxIDs are deprecated)
## 4. Taxa name
## 5. Taxa rank
## 6. Classification: is it correct at species, correct at higher or incorrect?
## 7. How many taxa far away from the correct one? If it’s correct at species level this number is 0, and if it’s incorrect it is also 0.



library(data.table)
library(ggplot2)


classifiers <- c("Centrifuge", "Kraken2", "DIAMOND", "MetaPhlAn2")
group <- c("raw", "cleaned")

## read the raw files
data <-NULL
for(g in group){
  for(i in classifiers){
    if(g == "raw"){
      tmp <- fread(paste0("/Users/sneuensc/Sapfo/virome_yami/human_sims/", i, "_hg19_Correct_Incorrect.tsv"))
    }else{
      tmp <- fread(paste0("/Users/sneuensc/Sapfo/virome_yami/human_sims/", i, "_hg19_cleaned_Correct_Incorrect.tsv"))
    }
    tmp$classifier <- i
    tmp$group <- g
    data <- rbind(data, tmp)
  }
}
colnames(data) <-c('reads','taxID','taxID2','taxName','rank','classification','rankLevel','classifier','group' )
data$classifier <- factor(data$classifier, levels=classifiers)


## add the total number of reads
data$reads.tot[data$group == "raw"] <-476876980
data$reads.tot[data$group == "cleaned"] <-468930547

## add the number of unclassified
dd <- data[,list('reads' = sum(reads)), by = c('classifier','group', "reads.tot")]
dd$Unclassified <- dd$reads.tot - dd$reads
dd$class <- "Unclassified"
dd$nan <- NaN

dd <- dd[,c('Unclassified','nan','nan','nan','nan','class','nan','classifier','group','reads.tot')]
colnames(dd) <- colnames(data)
data <- rbind(data, dd)

## add the number of cleaned reads
cleaned <- 476876980 - 468930547

data$classification <- factor(data$classification, levels = c('Correct_species','Correct_higher','Incorrect','Unclassified'))

data$group <- factor(data$group, levels = c("raw","cleaned"))

## replace missing values with 0
for(c in unique(data$classification)){
  for(l in unique(data$classifier)){
    if(length(data$reads[data$classification == c & data$classifier == l]) == 0){
      data <- rbind(data, list('reads' = 0, 'taxID' = NaN, 'taxID2' = NaN, 'taxName' = NaN, 'rank' = NaN, 
                               'classification' = c, 'rankLevel' = NaN, 'classifier' = l, 'group' = 'raw', 
                               reads.tot = 476876980))
    }
  }
}
  

data <- data[data$group == "raw",]

```


## extra taxa of incorrect classifications
```{r}
#d <- data[data$taxID != 1,]  ## remove classifications at the root
d <- data
FUN <- function(x) return(sum(x>0))
d <- d[,list('reads' = sum(reads), 'nb.taxa' = FUN(reads)), by = c('classifier','group', 'classification', 'reads.tot')]
d$reads <- as.numeric(d$reads)
d$reads.tot <- as.numeric(d$reads.tot)
d$nb.taxa <- as.numeric(d$nb.taxa)

d$props <- 100 * d$reads/d$reads.tot

colorcillos <- c(rgb(0, 158, 115, maxColorValue = 255),
                   rgb(181, 230, 0, maxColorValue = 255),
                   rgb(243, 155, 0, maxColorValue = 255),
                   rgb(213, 213, 213, maxColorValue = 255))

tmp <- d
#tmp <- d[d$group == "raw" & (d$classification == "Correct_species" | d$classification == "Incorrect" | d$classification == "Unclassified"),]
tmp$Classification <- as.character(tmp$classification)
tmp$Classification[tmp$Classification == "Correct_species"] <- "Correct species\n(classified as human)"
tmp$Classification[tmp$Classification == "Correct_higher"] <- "Correct higher"
tmp$Classification <- factor(tmp$Classification, levels = c("Correct species\n(classified as human)","Correct higher","Incorrect","Unclassified"))
tmp$props2 <- tmp$props 
tmp$props2[tmp$props == 0] <- NaN

a1 <- ggplot(tmp, aes(y = props, fill = Classification, x = classifier)) +
    geom_bar(stat="identity", position = position_dodge(preserve = "single")) +
    scale_fill_manual(values = colorcillos) +
    scale_color_manual(values = colorcillos) +
    geom_text(aes(label = as.character(round(props2,3)), 
              color = Classification), 
              #color = ifelse(tmp$props > 50, Classification, "black")), 
              position=position_dodge(width=0.9), 
              hjust = ifelse(tmp$props > 50, 1.1, -0.1),
              vjust=0.5, cex=3.5, angle=90) +
    geom_text(aes(label = ifelse(tmp$props > 50, as.character(round(props2,3)), "")), 
              #color = ifelse(tmp$props > 50, 'black', 'blue'), 
              position=position_dodge(width=0.9), 
              hjust = ifelse(tmp$props > 50, 1.1, -0.1),
              vjust=0.5, cex=3.5, angle=90) +
    ylab("% reads") +
    xlab("") +
    ylim(0,100) +
    ggtitle(title) +
    #scale_fill_discrete(name = "Classification", labels = c("Correct species","Incorrect")) +
    #guides(fill=guide_legend(title="Classification")) +
    theme_classic() +
    theme(legend.position=c(0.5, 0.8),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    ggtitle("A. Classification")
  
  a1
  
  
colors_bw <- c("black","gray")

a2 <- ggplot(d[d$classification == "Incorrect",], 
             aes(y = reads, x = classifier)) +
    geom_bar(stat="identity", position = position_dodge(preserve = "single"), fill = colorcillos[3]) +
    geom_text(aes(label = reads), position=position_dodge(width=0.9), vjust=-0.25, cex=3.5) +
    ylab("# incorrectly classified reads") +
    xlab("") +
    #ylim(0,100) +
    ggtitle(title) +
    #guides(fill=guide_legend(title="Cleaning")) +
    theme_classic() +
    theme(legend.position=c(0.3, 0.8),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    ggtitle("B. Incorrectly classified reads")
  
  a2
  
a3 <- ggplot(d[d$classification == "Incorrect",], 
             aes(y = nb.taxa, x = classifier)) +
    geom_bar(stat="identity", position = position_dodge(preserve = "single")) +
    scale_fill_manual(values = colors_bw) +
    geom_text(aes(label = nb.taxa), position=position_dodge(width=0.9), vjust=-0.25, cex=3.5) +
    ylab("# spurious extra taxa") +
    xlab("") +
    ggtitle(title) +
    guides(fill=guide_legend(title="Cleaning")) +
    theme_classic() +
    theme(legend.position=c(0.7, 0.8),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    ggtitle("C. Spurious extra taxa")
  
a3



file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/sam/figure_human_sims2.pdf"
  library(gridExtra)
  library(grid)
  
  lay <- rbind(c(1,1,2,3))
  grob <- grid.arrange(grobs=list(a1, a2, a3), layout_matrix=lay)   
  
  ggsave(file, width = 297, height = 210*2/3, scale=1.1, units = "mm", grob)
```




## get taxonomic tree
```{r}
library(taxonomizr)
library(dplyr)
## get db
path <- "/Users/sneuensc/Documents/Vital-IT/Sapfo/australia/NC_001422_sim_reads/"
getNamesAndNodes(path)                    # Function to download names.dmp and nodes.dmp from NCBI

# Create the sql databases
read.nodes.sql(paste0(path, 'nodes.dmp'), sqlFile = paste0(path, "nameNode.sqlite"), overwrite = FALSE) # First, add the nodes file
read.names.sql(paste0(path, 'names.dmp'), sqlFile = paste0(path, "nameNode.sqlite"), overwrite = FALSE)	# Secondly, add the names file


taxRanks<-as.data.frame(matrix(c("U", "unclassified",
                   "D", "domain",
                   "SK", "superkingdom",
                   "K", "kingdom",
                   "P", "phylum",
                   "C", "class",
                   "O", "order",
                   "F", "family",
                   "G", "genus",
                   "S", "species"), byrow=T, ncol=2))
colnames(taxRanks) <- c("abrev","rank")

d3 <- data[data$classification == 'Incorrect' & data$group == "raw",][,list('reads' = sum(reads)), by = c('taxID', 'taxName', 'classifier')]

## get the classification
d3 <- cbind(d3, getTaxonomy(ids = d3$taxID, sqlFile = paste0(path, "nameNode.sqlite"), desiredTaxa = taxRanks$rank))

## number of not found taxaIDs 
#d3[,list('N.NAs' = sum(is.na(species)), 'N' = .N), by='classifier']

FUN <- function(x){
  for(i in length(x):1){
    if(!is.na(x[i])) return(i)
    }
  return(NaN)
}
d3$rank <- apply(d3[,-(1:5)], 1, FUN)
d3[is.na(d3$rank)]

col.taxa <- data.frame(superkingdom = c("Bacteria","Archaea","Viruses","Eukaryota","other"), 
                       color = c('#61D04F', '#DF536B', '#2297E6', '#28E2E5','black'))

d5 <- d3[,list(N = .N), by = c('classifier','superkingdom')]
d5 <- d5[!is.na(d5$superkingdom),]
#d5$superkingdom[is.na(d5$superkingdom)] <- "other"
d5$superkingdom <- factor(d5$superkingdom, levels = col.taxa$superkingdom)
#d5 <- d5[order(d5$classifier, d5$color),]

my.pie <- NULL
for(c in classifiers){
  tmp <- d5[d5$classifier == c,]
  
  my.pie[[c]] <- ggplot(tmp, aes(x = "", fill= superkingdom, y = N)) +
    geom_bar(width = 1, stat = "identity", color = "white") +
    coord_polar("y", start = 0) +
    scale_fill_manual(values = col.taxa$color[col.taxa$superkingdom %in% tmp$superkingdom]) +
    geom_text(aes(label = N,  x = 1.2), 
              position = position_stack(vjust = 0.5),
              color = "white", cex=5) +
    theme_void()
  
  file <- paste0("/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/sam/figure_human_sims_taxRanks_",c,".pdf")
  ggsave(file, width = 85, height = 85, scale=1, units = "mm")
  
}



hist(d3$rank)

d4 <- d3[,list(N = .N), by = c('rank','classifier')]
d4$rank2 <- taxRanks$rank[d4$rank+1]
d4$rank2[is.na(d4$rank2)] <- "NA"
d4$rank2 <- factor(d4$rank2, levels=c("NA", taxRanks$rank))

maxx <- d4[,list(max = sum(N), NN = .N), by = 'classifier']
d4 <- merge(d4, maxx)
d4$max2[is.na(d4$rank)] <- d4$max[is.na(d4$rank)]


r <- ggplot(d4, aes(x = rank2, y = N)) +
  geom_bar(stat="identity") +
  xlab("taxonomic rank") +
  ylab("frequency in counts") +
  theme_classic() +
  #ylim(0,1246) +
  ggtitle("Taxonomic rank of classifed reads") +
  geom_text(aes(x = rank2, 
                y = ifelse(N > 1000, N - 250, N + 10), 
                label = paste0(N, " (", round(100*N/max,1), "%)")),
            color = ifelse(d4$N > 1000, "white", "black"),
            hjust = 0, vjust = 0.5, size = 3.5) +
  # geom_text(data = maxx, aes(x = NN/2, y = 1250, 
  #                           label = paste(max, "different taxas in total")), hjust = 1, vjust = 3.5) +
  facet_wrap(~classifier, scales = "free_y") +
  theme(legend.position = "none") +
  coord_flip() 
r

  # ymax <- max(apply(cur[,samples],2,sum))
  #   xmax <- length(samples)
  #   print(r + annotation_custom(ggplotGrob(my.pie[[1]]), xmin = 1, xmax = 10, ymin = 0, ymax = 1))


file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/sam/figure_human_sims_taxRanks.pdf"
ggsave(file, width = 297, height = 210*2/3, scale=1, units = "mm")

```

## plot data with most hits
```{r}
d <- data[data$classification == "Incorrect"  & data$group == "cleaned" & data$taxID != 1,]
d <- d[order(d$classifier, d$reads, decreasing = T)]



## get the first 20 rows per classifier
N <- 10
d1 <- d[, .SD[1:N], classifier]
d1$x <- rep(N:1, 4)

ggplot(d1, aes(x = x, y = reads)) +
  geom_bar(stat="identity") +
  xlab("number of reads per extra taxa") +
  ylab("") +
  theme_classic() +
  ggtitle("Most abundant extra taxa") +
  geom_text(aes(x = x, y = 0, label = taxName), hjust = 0, vjust = 0.5, color = "gray") +
  #geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(reads, "incorrectly classified reads")), hjust = 0, vjust = 3) +
  #geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(extra.taxa, "extra taxa")), hjust = 0, vjust = 5) +
  scale_x_discrete(labels = d1$taxName) +
  facet_wrap(~classifier, scales = "free") +
  coord_flip() 

file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/sam/figure_human_sims_abudantTaxa.pdf"
ggsave(file, width = 297, height = 210*2/3, scale=1.5, units = "mm")

```

## write Excel sheet with all hits
```{r}
d <- data[data$classification == "Incorrect"  & data$group == "cleaned" & data$taxID != 1,]
d <- d[order(d$classifier, d$reads, decreasing = T), c('reads','taxID','taxName','rank','classifier')]

library("xlsx")
file <- "/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/sam/human_simulation_extra_taxa.xlsx"
for(i in classifiers){
write.xlsx(d[d$classifier == i, -ncol(d), with = F], file, sheetName = i, 
  col.names = TRUE, row.names = F, append = T)
}

```


```{r}



library("ggVennDiagram")
for(rank in taxRanks$rank){
  #rank <- "order"  
  
  d <- d3
  d$cur.rank <- d[,rank, with =F]
  d <- d[,list(reads = sum(reads), N = .N), by = c('cur.rank', 'classifier')]
  
  d <- d[! is.na(d$cur.rank),]
  
  l <- list("Centrifuge" = d$cur.rank[d$classifier == 'Centrifuge' ],
            "Kraken2" = d$cur.rank[d$classifier == 'Kraken2' ],
            "DIAMOND" = d$cur.rank[d$classifier == 'DIAMOND' ],
            "MetaPhlAn2" = d$cur.rank[d$classifier == 'MetaPhlAn2'])
  
  
  ggVennDiagram(l, label_alpha = 0) +
    ggtitle(paste("Common extra taxa at the", rank, "level")) +
    theme(legend.position = "none")
  
  file <- paste0("/Users/sneuensc/Dropbox (popgen)/Virome/PLoS_ONE_virome/figure_human_venn_diagram_", rank, ".pdf")
  ggsave(file, width = 210, height = 210, scale=1.5, units = "mm")
}
```


```{r}

## sort
d <- d[order(d$classifier, d$reads, decreasing = T),]

## get x most hit taxa per classifier
dd <- d[ ,.SD[1:10], by = 'classifier']

#dd$reads <- factor(dd$reads, levels = sort(unique(dd$reads, decreasing = T)))

## hack to ge the rigth ordering
dd$order <- paste0("A", 1: nrow(dd))
dd$order <- factor(dd$order, levels = rev(dd$order))



ggplot(dd, aes(x = order, y = reads)) +
  geom_bar(stat="identity") +
  xlab("") +
  ylab("# reads") +
  theme_classic() +
  ggtitle(paste("Extra taxa of incorrectly classfied reads at the", rank, "level")) +
  #geom_text(aes(x = reads, y = max/100 + freq, label = taxID), hjust = 0, vjust = 0.5, size = 2.5) +
 # geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(reads, "incorrectly classified reads")), hjust = 0, vjust = 3) +
  #geom_text(data = nn, aes(x = Inf, y = 0.7*max, label = paste(extra.taxa, "extra taxa")), hjust = 0, vjust = 5) +
  facet_wrap(~classifier, scales = "free") +
  
  scale_x_discrete("name", breaks = 1:nrow(dd), labels = dd$cur.rank) +
  coord_flip() 
```





