# Config file for run_classifiers.smk

samples: ['ERR4093844']

# Centrifuge
path2Centrifuge: '/scratch/wally/FAC/FBM/DBC/amalaspi/popgen/yarizmen/virome/tools_scripts/Centrifuge/centrifuge-1.0.3-beta/centrifuge'
path2Centrifuge_db: '/scratch/wally/FAC/FBM/DBC/amalaspi/virome/yarizmen/simulations_Feb_2020b/abv'

# Kraken2
path2Kraken2: '/scratch/wally/FAC/FBM/DBC/amalaspi/popgen/yarizmen/virome/tools_scripts/kraken2-master/kraken2'
path2Kraken2_db: '/scratch/wally/FAC/FBM/DBC/amalaspi/virome/yarizmen/simulations_Feb_2020b/KRAKEN2database'

# DIAMOND
# path2DIAMOND: '/scratch/wally/FAC/FBM/DBC/amalaspi/popgen/yarizmen/virome/tools_scripts/DIAMOND/diamond-0.9.22/bin/diamond'
path2DIAMOND: '/scratch/wally/FAC/FBM/DBC/amalaspi/popgen/sneuensc/virome_yami/diamond'
path2DIAMOND_db: '/scratch/wally/FAC/FBM/DBC/amalaspi/virome/yarizmen/simulations_Feb_2020b/Viral_tax'

# MetaPhlAn2
path2MetaPhlAn2: '/scratch/wally/FAC/FBM/DBC/amalaspi/popgen/yarizmen/virome/tools_scripts/MetaPhlan2/metaphlan2/metaphlan2.py'

api_key: "8f5a7ee70253e037c5641bab48b0d6d74908"

# From MetaPhlAn2 names to taxIDs
#path2Rscript: '/scratch/wally/FAC/FBM/DBC/amalaspi/popgen/yarizmen/virome/tools_scripts/MetaPhlAn2_labels_2_taxIDs.R'
path2Rscript: '/scratch/wally/FAC/FBM/DBC/amalaspi/virome/yarizmen/simulations_classifiers/classifiers/MetaPhlAn2_labels_to_taxIDs_v2.R'